base_checkpoint: "./checkpoints/dune_vitbase14_448_paper.pth"
realm_checkpoint: "./checkpoints/REALM_final_rank32_0955116.pth"
embedding:
  num_bins: 5
  patch_grid: 32
  embed_dim: 768
  base_channels: 64
  num_downsample: 3
  norm: batch
  use_residual: True
pretrained_head: "./checkpoints/heads/depth.pth"
head: 
  type: depth
  embed_dim: 768
  min_depth: 1.95
  max_depth: 82.0
  num_bins: 256

data:
  batch_size: 32

  datasets_config:
    datasets:
      - MVSEC
      
    common:
      events_representation: voxel_grid
      nr_bins_per_data: 5
      normalize_event: true
      sequence_length: 1
      target_size: [346, 260]

    MVSEC:
      root: ./datasets/MVSEC
      n_ev: 150000
      ms_ev: -1
      stride: 1
      mask: true
      skip_init_frames: 1
      depth: true
      min_n_ev: 5000
      transforms:
        - type: resize
          params:
            target_size: [260, 346]
            keep_aspect_ratio: true